JD-1415. Raw implementation of expressions function added
atlascommunity/jira-plugins-groovy pull request #113
Opened 2021-05-17 21:47 UTC by Raschudesny

Still very raw implementation of expression function. 

1. There is no support for jira-way  jql short dates like: 1w, 2d, 3wd etc...
2. There is no support for JQL function calls, like now(), currentUser() and others
3. GroovyShell runs is not safe (maybe there is possibility for some security vulnerabilities here)
4. Right now all script execution fails will cause RuntimeError in getQuery function. This is not good way to deal with them because most of the user input errors (like adding or comparing not comparable types) can be found only during script execution. On the other hand jira api forces all the jql-functions to show input errors on validate() stage.

2021-05-18 08:14 UTC, mashintsev requested changes

2021-05-18 08:14 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +        InputStream resourceAsStream = getClass().getClassLoader().getResourceAsStream("AdditionalArithmeticOperators.groovy");
обернуть в try with resource

2021-05-18 08:14 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +                jqlClauseBuilder.addClause(JqlQueryBuilder.newClauseBuilder().customField(Long.valueOf(cfId)).isNotEmpty().buildClause());
Кажется можно заменить  JqlQueryBuilder.newClauseBuilder().customField(Long.valueOf(cfId)
на 
JqlQueryBuilder.newClauseBuilder().field(fieldId)

2021-05-18 08:14 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +                jqlClauseBuilder.addClause(JqlQueryBuilder.newClauseBuilder().field(clauseInformation.getJqlClauseNames().getPrimaryName()).isNotEmpty().buildClause());
а почему тут не используется fieldId ?

2021-05-18 08:14 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +                String cfId = fieldId.replaceAll("customfield_", "");
Вот эта конструкция странная. Если JqlQueryBuilder.newClauseBuilder().field(fieldId) работает, то нужно убрать replace

2021-05-18 08:14 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +    }
метод странный. Точно нельзя достать fieldId и сравнить их?

2021-05-18 08:14 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +        visitor.clear();
Так получается что visitor пошариться между потоками и будет так себе результат этого блока

2021-05-18 08:14 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +public class ExpressionFunction extends AbstractBuiltInQueryFunction {
а точно это должен быть Component?

2021-05-18 08:14 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +        Script parsedScript = groovyShell.parse(expressionQueryStr);
в этот скрипт все что угодно можно записать? Если да, то нужно думать как ограничить набор выражений.

2021-05-19 15:15 UTC, Raschudesny commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +public class ExpressionFunction extends AbstractBuiltInQueryFunction {
Ну да, а почему нет :)

2021-05-19 15:16 UTC, Raschudesny commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +    }
Так смысл в том что всё что у нас есть изначально, это лишь имя поля и мы уже по именам полей ищем соответсвующие им ClauseInformation-ы. 
Поэтому да, тут нельзя просто так взять и достать fieldId для поля, потому что мы банально его ещё не знаем на этой стадии. 
Но я там нашел можно просто из customFieldManger-а кастомфилды доставать по имени, тогда этот метод будет не нужен.

2021-05-19 15:21 UTC, Raschudesny commented on src/main/java/ru/mail/jira/plugins/groovy/impl/jql/function/builtin/expression/ExpressionFunction.java
> +                jqlClauseBuilder.addClause(JqlQueryBuilder.newClauseBuilder().customField(Long.valueOf(cfId)).isNotEmpty().buildClause());
Там у JqlQueryBuilder.newClauseBuilder().field(fieldId) метода, сигнатура ConditionBuilder field(String jqlName)
С кастомфилдами там вообще так не сработает, потому что для них jql выражение же должно выглядеть типа как 
cf[cfID] operator operand
Поэтому функция customField(Long.valueOf(cfId)) и принимает лонг и там его преобразовывает в "cf[" + cfId + "]"

2021-05-20 07:14 UTC, mashintsev approved these changes

2021-05-20 07:14 UTC, merged