fix scripted fields permalink
atlascommunity/jira-plugins-groovy pull request #129
Opened 2021-09-18 15:02 UTC by Bezneima

2021-09-20 09:16 UTC, mashintsev requested changes

2021-09-20 09:16 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/repository/AuditLogRepositoryImpl.java
> +        if (category.toString().equals("CUSTOM_FIELD")) {
зачем делать у enum tostring и сравнивать со строкой?

2021-09-20 09:16 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/repository/AuditLogRepositoryImpl.java
> +            result.setUrl(ScriptUtil.getPermalink(category, activeObjects.get(FieldScript.class, entityId).getFieldConfigId().intValue()));
Тут возможно ли тут NPE при доступе к activeObjects.get(FieldScript.class, entityId).getFieldConfigId() ?

2021-09-20 09:16 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/groovy/impl/repository/AuditLogRepositoryImpl.java
>          fillEntityData(result, category, entityId);
вообще стоит перенести эту функцию выше и тогда можно брать id для permalink из поля scriptId

2021-09-21 17:18 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/groovy/impl/repository/AuditLogRepositoryImpl.java
> +        if (category.toString().equals("CUSTOM_FIELD")) {
поменял на enum

2021-09-21 17:19 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/groovy/impl/repository/AuditLogRepositoryImpl.java
> +            result.setUrl(ScriptUtil.getPermalink(category, activeObjects.get(FieldScript.class, entityId).getFieldConfigId().intValue()));
поставил условие

2021-09-21 17:20 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/groovy/impl/repository/AuditLogRepositoryImpl.java
>          fillEntityData(result, category, entityId);
перенес в функцию которая возвращает id

2021-09-22 11:28 UTC, mashintsev approved these changes

2021-09-22 11:29 UTC, merged